### ISSUE TITLE
Issue with assembling FMA dataset

### ISSUE THREAD

**Issue by xuan301** [feizc/FluxMusic#26]
**Description:**
I am encountering an issue while attempting to train a model using the FMA dataset. I need guidance on how to run the `def fma_dataset()` function in test.py, and I've noticed a discrepancy in the dataset files available at huggingface.

**Steps to Reproduce:**
1. I am trying to assemble the FMA dataset for training purposes.
2. This is the following code snippet in test.py which is supposed to set up the dataset:
```python
import pandas as pd
annotation_prex = "/maindata/data/shared/public/zhengcong.fei/dataset/dataset_music/annotation"
annotation_list = ['test-00000-of-00001.parquet', 'train-00000-of-00001.parquet', 'valid-00000-of-00001.parquet']
```

**Additional Information:**
- The link provided [here](https://huggingface.co/datasets/benjamin-paine/free-music-archive-large/tree/main/data) seems to contain only the training dataset, with a total of 171 Parquet files, and I don't know which one to be used.

**Questions:**
Are there alternative sources or methods to obtain the needed FMA dataset and its annotation(`train-00000-of-00001.parquet`, `test-00000-of-00001.parquet` and `valid-00000-of-00001.parquet`)?

Thank you for your assistance. I look forward to resolving this issue to proceed with my training.
Best regards

**Comment by eftSharptooth** [comment]
I believe you are actually looking for enrich-fma-large dataset to meet the three parquet files requested here.

**Comment by xuan301** [comment]
That's it, thanks for your help!
