### ISSUE TITLE
Horrible results locally compared to the website/app melodio.ai

### ISSUE THREAD

**Issue by foureyednymph** [feizc/FluxMusic#6]
How are we also able to change the input and lyrics manually?

**Comment by feizc** [comment]
Hi, the current relased is 200K-steps ckpts, that are trained on a sub-training set and used for plotted the scaling experiments as well as case studies in the paper. 
The full version of main results will be realsed right way.
I am sorry to make you confused 🙇 and we have updated the readme.
( I only hope to promote our own products

**Comment by foureyednymph** [comment]
@feizc No problem!! very excited😁💕

**Comment by foureyednymph** [comment]
I have a question, does that mean that fluxmusic and melodio are basically just different models? if they are then i got my hopes up too high. 😅 @feizc

**Comment by feizc** [comment]
Hi, to be honest, the structure is same, but the training strategy is slightly different (we only provided pre-training with open-source data, and we will fine tuned high-quality copyrighted data before in use), as well as some re-writing and post-processing optimization.

**Comment by Nacholmo** [comment]
> and we will fine tuned high-quality copyrighted data before in use), as well as some re-writing and post-processing optimization. 

Probably it's a good idea to not say this type of thing to avoid getting sued. Some companies are pretty sensible to people training in their copyrighted work and they are in search for a legal precedent, even if it's open source

**Comment by fakerybakery** [comment]
> Hi, to be honest, the structure is same, but the training strategy is slightly different (we only provided pre-training with open-source data, and we will fine tuned high-quality data before in use), as well as some re-writing and post-processing optimization.

Cool! Are there any plans to add support for lyric generation similar to the webapp?
